### PR TITLE
Fix orbit-controls dist and update to OrbitControls r158

### PR DESCRIPTION
**Pull request by vincentfretin**
From comments in #331 it appears the minified build of orbit-controls is empty and the OrbitControls module is missing even is the non minified build. I'm not sure what happened when you did the 1.3.1 release @dmarcos 
I just did again:
```
cd components/orbit-controls
rm -rf node_modules/ package-lock.json
npm i
npm run dist
```

The dist are fine now.

### CODE REVIEW

**Comment by vincentfretin** [comment]
I also updated OrbitControls to r158 and added the new options and updated documentation.

**Comment by dmarcos** [comment]
thanks. I just published. let me know if it looks right.

**Comment by vincentfretin** [comment]
Thank you, it works great!

**Comment by vincentfretin** [comment]
A mistake in the code snippet in the README slipped in. Fix in #333

**Pull request merged**
